### ISSUE TITLE
CachedSerializer 'Out of memory'

### ISSUE THREAD

**Issue by adem0x** [d-mozulyov/CachedTexts#1]
I am trying to familiarize myself with this code; and to help with that, I turned the console demo (CachedSerializer) into a GUI one.

It is a simple enough thing to do. I did not modify any of the underlying code, just added a Memo and a couple of other niceties.

But.. when I run it (specifically against the 'html_tags.txt' in the 'examples' folder), I get an 'out of memory' error.

This same file is parsed without any error in the console app, but not in GUI app.

I tried to debug it, but it didn't go anywhere.

Could you look into this please.

PS: I have enclosed the project sources.
[CachedSerializerGUI.zip](https://github.com/d-mozulyov/CachedTexts/files/3273419/CachedSerializerGUI.zip)

**Comment by d-mozulyov** [comment]
Hi, adem0x

The problem is that the TSerializeOptions is a record, so it should be set 0 before usage.
```pascal
  Memo1.Lines.Clear;
  {Finalize(Options1); - reuse case}
  FillChar(Options1, SizeOf(Options1), #0); // <-- here
  Options1.AddFromFile(AFileName, True);
```

**Comment by adem0x** [comment]
Thank you, Dimitry, for the prompt reply.

it never occured me than I needed to initialize TSerializeOptions.

I suspect other people will be in my position.

To avoid that, may I suggest that the following are added to TSerializer:

```
  TSerializer = class(TObject)
    {...}
  public
    {since TSerializeOptions is a record, you need to call this before using this TSerializer}
    class procedure InitializeOptions(var Options: TSerializeOptions);
    class procedure FinalizeOptions(var Options: TSerializeOptions); {to re-use}
    {...}
  end;

```  
and in the implementation section, add these 2 procedures:

```
class procedure TSerializer.InitializeOptions(var Options: TSerializeOptions);
begin {since TSerializeOptions is a record, you need to call this before using this TSerializer}
  FillChar(Options, SizeOf(TSerializeOptions), #0);
end;

class procedure TSerializer.FinalizeOptions(var Options: TSerializeOptions);
begin
  Finalize(Options);
end;

```

**Comment by d-mozulyov** [comment]
I've added TSerializeOptions.Clear method support. Please, update the sources.

**Comment by adem0x** [comment]
Elegant.

Thank you.

**Comment by d-mozulyov** [comment]
You're welcome :)
